package net.labyfy.component.config.annotation;

import net.labyfy.component.stereotype.annotation.Transitive;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks an interface inside a {@link Config} as already implemented and not to be autogenerated, more information can
 * be found in the {@link Config}.
 *
 * @see Config
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Transitive
// marks an interface in a @Config not to be automatically implemented
public @interface Implemented {

}
